#!/bin/bash
echo "postinst"

# Create the logging directory
LOG_DIRECTORY=/var/log/
LOG_FILE1=$LOG_DIRECTORY/orangedb.log
LOG_FILE2=$LOG_DIRECTORY/orangedb.json
mkdir -p $LOG_DIRECTORY
touch $LOG_FILE1
touch $LOG_FILE2
chown appuser:appuser $LOG_FILE1
chown appuser:appuser $LOG_FILE2

# Set the directory permissions
chown appuser:appuser /home/appuser/*
cd /home/appuser/docussandra-api
jar -xf /home/appuser/orangedb-api/orangedb-api-jar-with-dependencies.jar

# Stop the service if its running
if [ -f /var/run/orangedb.pid ];
then
   stop orangedb-api
fi

# Start the service
start orangedb-api
